INSERT INTO TB_USUARIO(nome, email, senha, telefone) VALUES ('Paulo Henrique', 'ph23.alves@gmail.com', '123', '11972266510');
INSERT INTO TB_USUARIO(nome, email, senha, telefone) VALUES ('Beatriz Torres', 'beatriztorres@gmail.com', '123456', '11934455434');
INSERT INTO TB_USUARIO(nome, email, senha, telefone) VALUES ('Vanessa Camargo', 'vanessa.camargo@gmail.com', '123456', '11823344562');
INSERT INTO TB_USUARIO(nome, email, senha, telefone) VALUES ('Alexandre Neto', 'ale.neto@gmail.com', '123', '11946677654');

INSERT INTO TB_CATEGORIA(nome) VALUES ('Restaurante');
INSERT INTO TB_CATEGORIA(nome) VALUES ('Hotel');
INSERT INTO TB_CATEGORIA(nome) VALUES ('Shopping');
INSERT INTO TB_CATEGORIA(nome) VALUES ('Pet Shop');
INSERT INTO TB_CATEGORIA(nome) VALUES ('Colégio');
INSERT INTO TB_CATEGORIA(nome) VALUES ('Salão de Beleza');	
INSERT INTO TB_CATEGORIA(nome) VALUES ('Farmácia');	
INSERT INTO TB_CATEGORIA(nome) VALUES ('Padaria');	

INSERT INTO TB_AVALIACAO(categoria_id, comentario, data, nota, usuario_id) VALUES (1, 'Muito bom', '2019-10-10', 5, 1);
INSERT INTO TB_AVALIACAO(categoria_id, comentario, data, nota, usuario_id) VALUES (1, 'Incrível!!', '2022-10-10', 4, 2);


-- INSERT INTO TB_ESTABELECIMENTO(contato, descricao, endereco, horario_funcionamento, imagem, local, nome, nota, site) VALUES ('11972266510', 'Restaurante muito bom', 'Rua dos Bobos, 0', '2019-10-10', 'imagem', 'São Paulo', 'Restaurante do Paulão', 5, 'www.restaurantedopaulao.com.br');

    -- private Long id;
    -- private float nota;
    -- private String nome;
    -- private String site;
    -- private String local;
    -- private Byte imagem;
    -- private String contato;
    -- private String endereco;
    -- private String descricao;
    -- private LocalDateTime horarioFuncionamento;

    --  create table tb_estabelecimento (
    --    id bigint generated by default as identity,
    --     contato varchar(255),
    --     descricao varchar(255),
    --     endereco varchar(255),
    --     horario_funcionamento timestamp(6),
    --     imagem tinyint,
    --     local varchar(255),
    --     nome varchar(255),
    --     nota float(24) not null,
    --     site varchar(255),
    --     primary key (id)
    -- )


-- INSERT INTO TB_AVALIACAO(nota, criado_em, comentario, dono_id) VALUES (5, '2019-10-10', 'Muito bom', 1);
-- INSERT INTO TB_AVALIACAO(nota, criado_em, comentario, dono_id) VALUES (5, '2019-10-10', 'Muito bom', 2);
-- INSERT INTO TB_AVALIACAO(nota, criado_em, comentario, dono_id) VALUES (5, '2019-10-10', 'Muito bom', 3);

-- INSERT INTO TB_ESTABELECIMENTO()
